### ISSUE TITLE
Flatpak builds, publish to Flathub

### ISSUE THREAD

**Issue by orowith2os** [benjamimgois/goverlay#34]
Currently, using goverlay requires it be installed using a native package manager, and that + the fact that, at least for me, it behaves weirdly outside of a sandbox of some sort (and I use an immutable distro)

I can start work on a basic manifest sometime later, and then work out the kinks from there---

**Comment by orowith2os** [comment]
I just did a quick grep of the repo to see anything that would need to be changed, and *oh my lord* this is more than just spaghetti code

some suggestions are to stop hard-coding /usr/, and instead search the appropriate environment variables, such as $PATH, maybe switch to a different buildsystem, and generally clean up the codebase

**Comment by orowith2os** [comment]
oh this uses Pascal yeah that makes sense as to why it's so confusing

**Comment by benjamimgois** [comment]
This is the best i can do @orowith2os . But i'll try to improve the code with time.

**Comment by csc-chicken** [comment]
Good! I tried in #30 as well, how about now??

**Comment by csc-chicken** [comment]
@orowith2os I tried to build one, I forked it and build a flatpak. Now it lacks qt5pas dependency, do anyone have some ideas how to add qt5pas module into manifest??
below I copy module qt5pas from peazip and not work with goverlay.
the manifest
https://github.com/csc-chicken/goverlay/blob/test-flatpak/flatpak.mangohud.goverlay.yml

```yaml

id: flatpak.mangohud.goverlay
runtime: org.freedesktop.Platform
runtime-version: '22.08'
sdk: org.freedesktop.Sdk
sdk-extensions:
  - org.freedesktop.Sdk.Extension.freepascal
#command: start_goverlay
finish-args:
  - --allow=devel
  - --allow=multiarch
  - --share=network
  - --share=ipc
  - --socket=x11
  - --socket=wayland
  - --socket=pulseaudio
  - --device=all
  - --filesystem=xdg-download
  - --system-talk-name=org.freedesktop.UDisks2
  - --env=PATH=/app/bin:/app/utils/bin:/usr/bin:/usr/lib/extensions/vulkan/MangoHud/bin/:/usr/bin:/usr/lib/extensions/vulkan/OBSVkCapture/bin/
 

modules:
  #- name: MangoHud
  # build-options:
  #   arch:
  #     x86_64: *x86_64-build-options
  #   config-opts:
  #     - -Dmangoapp=true
  # buildsystem: meson
  # config-opts: &mangohud-config-opts
  #   - -Duse_system_vulkan=enabled
  #   - -Dvulkan_datadir=/usr/share
  #   - -Dwith_xnvctrl=enabled
  #   - -Dappend_libdir_mangohud=false
  #   - -Dmangoapp_layer=true
  # sources: &mangohud-sources
  #   - type: archive
  #     url: https://github.com/flightlessmango/MangoHud/releases/download/v0.6.8/MangoHud-v0.6.8-Source.tar.xz
  #     sha256: 9c64ccab1a72ba1dc61cb88d2fbcce1d343fc6b6cdf22c2cc2859bfb2da66fd4
  #     x-checker-data:
  #       type: json
  #       url: https://api.github.com/repos/flightlessmango/MangoHud/releases
  #       url-query: |
  #         map(select(.tag_name | startswith("v"))) | first |
  #         .assets | map((select(.name | endswith("Source.tar.xz")))) | first | .browser_download_url
  #       version-query: |
  #         map(select(.tag_name | startswith("v"))) | first |
  #         .tag_name | sub("^[vV]"; "")
  #- name: mangohud
  #  buildsystem: meson
  #  build-commands:
  #  - 
  #  sources:
  #    - type: archive
  #      url: https://github.com/flightlessmango/MangoHud/releases/download/v0.6.8/MangoHud-v0.6.8-Source.tar.xz
  #      sha256: 9c64ccab1a72ba1dc61cb88d2fbcce1d343fc6b6cdf22c2cc2859bfb2da66fd4
  #

  - name: qt5pas
    config-opts:
      - -after
      - target.path=/app/lib
    buildsystem: qmake
    sources:
      - type: shell
        commands:
          - cp -r /usr/lib/sdk/freepascal/share/lazarus/lcl/interfaces/qt5/cbindings/.
            .

  - name: start_goverlay
    buildsystem: simple
    build-commands:
    - install -D start_goverlay.sh /app/bin/start_goverlay.sh
    sources:
      - type: file
        path: start_goverlay.sh


```

**Comment by orowith2os** [comment]
If it has QT dependencies, it should be using the KDE runtime/SDK, not freedesktop.

**Comment by orowith2os** [comment]
I've made a repo containing a base manifest with a build workflow, I'll invite you (@csc-chicken) as a collaborator.

https://github.com/orowith2os/goverlay-flatpak

**Comment by csc-chicken** [comment]
@orowith2os how to accept as collaborator?? where can I see invitation? newbies here

**Comment by csc-chicken** [comment]
I copied cudatext manifest module for qt5pas and it freezed my computer twice when building .
https://github.com/flathub/io.github.cudatext.CudaText-Qt5/blob/master/io.github.cudatext.CudaText-Qt5.yml
```yaml
modules:
  - name: qt5pas
    sources:
      - type: archive
        url: https://gitlab.com/freepascal.org/lazarus/lazarus/-/archive/lazarus_2_2_0/lazarus-lazarus_2_2_0.tar.gz
        sha256: 37867f20be348787f1d783d0867573a838a448e19d36dd6e3b5cd71763c38db5
        dest: src/lazarus
    buildsystem: simple
    build-commands:
      - cp -r src/lazarus/lcl/interfaces/qt5/cbindings/. .
      - sed -e"s/target.path = .\+/target.path = '\/app\/lib'/" -i ./Qt5Pas.pro
      - qmake -makefile
      - make -j
      - make install

```
